version: '2'

services:
    pinba:
        image: choobs/mariadb:pinba
        # image: vendelev/pinba:latest
        # image: tony2001/pinba
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=123
        ports:
             - "30002:30002/udp"
             - "3306:3306"
    jinba:
        image: node:latest
        restart: always
        depends_on:
            - pinba
        links:
            - pinba
        volumes:
            - ./src:/var/www:rw
        working_dir: /var/www/jinba
        command: ["/bin/sh", "-c", "npm install && node index.js"]
    pinboard:
        image: lebnik/pinboard
        restart: always
        depends_on:
            - pinba
        links:
            - pinba
        volumes:
            - ./config/pinboard/parameters.yml:/var/www/pinboard/config/parameters.yml
            - ./config/pinboard/php.ini:/etc/php5/fpm/conf.d/99-custom.ini:ro
            - ./config/pinboard/fpm-pool.conf:/etc/php5/fpm/pool.d/www.conf:ro
            - ./config/pinboard/nginx.conf:/etc/nginx/sites-enabled/pinboard.conf
            - ./logs:/var/nginx_logs:rw
        working_dir: /var/www/pinboard
    proxy:
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
        depends_on:
            - jinba
            - pinboard
        links:
            - jinba
            - pinboard
        volumes:
            - ./:/var/www:rw
            - ./config/nginx/sites.conf:/etc/nginx/conf.d/sites.conf