version: '2'

services:
    pinba:
        image: choobs/mariadb:pinba
        # image: vendelev/pinba:latest
        # image: tony2001/pinba
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=123
        ports:
             - "30002:30002/udp"
             - "3306:3306"
    jinba:
        image: node:latest
        restart: always
        depends_on:
            - pinba
        links:
            - pinba
        volumes:
            - ./src/jinba:/var/www/jinba:rw
        working_dir: /var/www/jinba
        command: ["/bin/sh", "-c", "npm install && node index.js"]
    pinboard:
        image: vendelev/pinboard
        restart: always
        depends_on:
            - pinba
        links:
            - pinba
        volumes:
            - ./config/pinboard/parameters.yml:/var/www/pinboard/config/parameters.yml
            - ./logs:/var/www/logs:rw
        working_dir: /var/www/pinboard
    php:
        image: axiles89/php-fpm
        restart: always
        depends_on:
            - pinba
        links:
            - pinba
        volumes:
            - ./config/php/pinba.ini:/etc/php/7.0/fpm/conf.d/20-pinba.ini
            - ./config/php/pinba.ini:/etc/php/7.0/cli/conf.d/20-pinba.ini
            - ./src/php:/var/www/web:rw
        working_dir: /var/www/web
    proxy:
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
        depends_on:
            - jinba
            - pinboard
            - php
        links:
            - jinba
            - pinboard
            - php
        volumes:
            - ./config/nginx/sites.conf:/etc/nginx/conf.d/sites.conf
            - ./logs:/var/www/logs