version: '2'

services:
    pinba:
        image: choobs/mariadb:pinba
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=123
        ports:
#             - "3307:3306"
             - "30002:30002/udp"
        volumes:
            - ./data/pinba:/var/lib/mysql
    jinba:
        image: node:latest
        restart: always
        depends_on:
            - pinba
        links:
            - pinba
        volumes:
            - ./src/jinba:/var/www/jinba:rw
        working_dir: /var/www/jinba
        command: ["/bin/sh", "-c", "npm install && node index.js"]
    pinboard:
        image: vendelev/pinboard:latest
        restart: always
        depends_on:
            - pinba
        links:
            - pinba
        volumes:
            - ./config/pinboard/parameters.yml:/var/www/pinboard/config/parameters.yml
            - ./logs:/var/www/logs:rw
        working_dir: /var/www/pinboard
    proxy:
        image: nginx:latest
        restart: always
        ports:
            - "8081:80"
        depends_on:
            - jinba
            - pinboard
        links:
            - jinba
            - pinboard
        volumes:
            - ./config/nginx/sites.conf:/etc/nginx/conf.d/sites.conf
            - ./logs:/var/www/logs
