db:
    host: pinba
    name: pinba
    user: root
    pass: 123
base_url: /
logging:
    long_request_time:
        global: 0.099
    heavy_request:
        global: 6144
    heavy_cpu_request:
        global: 0.1
locale: en
cache: apc
records_lifetime: P1M
aggregation_period: PT15M
pagination:
    row_per_page: 50
secure:
    enable: true
    users:
        user1:
            password: VR+mgiSMxYKYyUnmhpr8Fjk+pSrXLuNAn+mmLWxvwNszsDNpvlbrhHkVU9pn43F3DggBrvEMPzG3UmC+NoehKw==
